version: "3.7"
services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: ./dockerfiles/php/Dockerfile
    image: urls
    container_name: urls-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - urls

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: urls-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockerfiles/mysql:/docker-entrypoint-initdb.d
    networks:
      - urls

  nginx:
    image: nginx:alpine
    container_name: urls-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    networks:
      - urls
  node:
    image: node
    restart: "no"
    container_name: urls-node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - urls
networks:
  urls:
    driver: bridge
