version: "3.7"
services:
  php:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: ./dockerfiles/php/Dockerfile
    image: urls
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockerfiles/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    networks:
      - laravel
  node:
    image: node:15
    restart: "no"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
